.travis/check_files.py
.travis/travis.sh

In PR check, see that tools are not already installed (check .yml files in this repo)

Check for installed tools in travis check

---

.travis/check_files.py
.travis/travis.sh
automated_tool_installation_log.tsv
usegalaxy.org.au/convert_formats.yml
usegalaxy.org.au/fastq_quality_control.yml
usegalaxy.org.au/metabolomics.yml
usegalaxy.org.au/metagenomic_analyses.yml

This reverts commit d00a964fbbd6fdfd6732132518a3473a3b48fab3.

Revert an unintended commit

---

jenkins/install_tools.sh
jenkins/main.sh

Commit the exact output of split_tool_yml.py to the tool directories and remove outdated files.

Update jenkins script to remove tool .yml files

---

.travis/check_files.py

Travis should not raise an error for installed tools

---

jenkins/install_tools.sh

fix test json overwriting the file
.

fix test json in install script

---

scripts/organise_request_files.py
trusted_owners.yml

Addresses #58 
yaml file containing trusted owners and blacklists (list of tool names not to automatically update) for each owner

Add blacklist option for trusted tool owners

---

requests/goseq.yml

https://support.ehelp.edu.au/helpdesk/tickets/75931

Added goseq as per user request

---

.travis/check_files.py
requests/machine_learning.yml

Add new section 'Machine Learning' and tools for tutorials

machine learning tutorial tools

---

requests/machine_learning2.yml

Additional tool required for classification and regression tutorial

Machine learning 2

---

requests/remaining_statistics_tutorial_tools.yml

Tools required for 'Age prediction using machine learning' and 'Interval-Wise Testing for omics data' tutorials

Remaining statistics tutorial tools

---

requests/smagexp.yml

adding user request smagexp

---

jenkins/install_tools.sh
jenkins/main.sh
jenkins/requirements.txt
scripts/organise_request_files.py

Use python3 virtual environments on jenkins.  Add planemo (planemo was refusing to run on python2)

Python3 virtual environment, use ephemeris 0.10.5, add planemo 0.70.0

---

jenkins/install_tools.sh

also increase sleep by 1 minute

add galaxy-wait for toolshed

---

scripts/write_report_from_log.py

```
- aaa revision abc, def was installed
```
instead of 
```
- aaa revision abc was installed
- aaa was update to revision def
```

update report script to account for tools that are installed and updated within the same week

---

requests/maxquant.yml

maxquant (from tool request form)

---

requests/diamond.yml

Install diamond to section 'Blast +'
issue #134

add tool diamond (user request)

---

scripts/write_report_from_log.py

Update report script to list installed tools before updated tools

update report script

---

requests/augustus_training@latest.yml
requests/jcvi_gff_stats@latest.yml

Retry tools that did not install due to api issues

retry tools augustus_training, jcvi_gff_stats

---

requests/kallisto_quant@60f888039fb2.yml
requests/minimap2@53c0b7a1a0c3.yml
requests/salmon@e3d32471da11.yml

salmon (passed 6/7), minimap2 (7/8) and kallisto_quant (6/7) now good to go.  They pass all their .bam file diff tests, the only remaining failures are test data table related.

[FORCE] install tools salmon, minimap2, kallisto_quant

---

.travis/check_files.py
requests/quasitools.yml

quasitools request

---

requests/transcriptomics.yml

Mostly iuc tools but there are two with owner 'rnateam'

transcriptomics tutorial tools

---

requests/missing_tools_versions.yml

Tools for some workflows published on Galaxy Europe (helpdesk ticket 80799)

tools for metaP, metaG, metaT workflows

---

requests/proteomics.yml

Tools for GTN proteomics workflows (excluding 'proteogenomics-novel-peptide-analysis', 'biomarker_selection' and 'proteome_annotation')

Proteomics tutorial tools

---

requests/cdhit.yml

install cdhit (from tool request form)

---

requests/top20_request.yml

proteomics.ms.tools first 5 from top 20 list

---

requests/pipe_t.yml

user request pipe_t

---

requests/cummerbund@c3b54a4b7741.yml

All 13 tests compare png files by diff and they fail, but the images appear to be the same.

[FORCE] cummerbund from update_24

---

requests/fastqe.yml

@slugger70 if this passes lint I'll merge it as admin
for tool request issue #237

fastqe (fastq with emojis)

---

requests/tuberculosis.yml

New tutorial written by Simon and co

tools for new tuberculosis variant calling tutorial

---

requests/nanocompore.yml

nanocompore tools

---

requests/salmon@b265be7af3db.yml

failed a test due to test using reference data

[FORCE] salmon from update_25

---

requests/snp_sites.yml

snp_sites (user tool request)

---

requests/cholhee_rna_tools.yml

request for mirdeep2 tools

---

requests/rgrnastar@5ec75f5dae3c.yml

rgrnastar never passes all of its tests because some of them use reference data

[FORCE] rgrnastar from update 27

---

requests/featurecounts.yml

featurecounts has a test that uses reference data so it fails, other tests are OK

[FORCE] install featurecounts

---

requests/genrich@latest.yml
requests/hicexplorer_hiccorrectmatrix@latest.yml

Both tools failed tests with errors that could be due to filesystem issues.  Try again.
https://github.com/usegalaxy-au/usegalaxy-au-tools/pull/277
https://github.com/usegalaxy-au/usegalaxy-au-tools/pull/274

retry genrich, hicexplorer_hiccorrectmatrix from install_430

---

requests/jbrowse@17359b808b01.yml

This is fine, a test always fails because of user name and id in the output file

[FORCE] jbrowse from update_30

---

requests/mike_tools.yml

follow up to https://github.com/usegalaxy-au/usegalaxy-au-tools/pull/298

Mike's metadegalaxy tools

---

requests/metadegalaxy.yml

metadegalaxy tools again

---

requests/computational_chemistry_new_tools_and_updates.yml

tools for new tutorial
update tools for gromacs tutorial

new computational chemistry tutorial tools

---

jenkins/requirements.yml

this might help with some current issues installing tools on new staging

use latest ephemeris (not released) from github

---

jenkins/new_server_tools.sh
jenkins/new_server_tools_skip_list.txt
scripts/organise_request_files.py

Tools that will not install + trinotate because its tests take ~4 hours each and there are 3 revisions.

skip list for install script

---

requests/mash.yml

mash tool request

---

requests/cardinal_preprocessing@6b36be80febb.yml
requests/cardinal_spectra_plots@c5aa9fca18c6.yml
requests/rgrnastar@e132e7d02a3e.yml

cardinal tools will have issues with parallel tests until the test framework is updated (21.01) but they pass one-by-one.  rgrnastar failed tests with data tables.

[FORCE] cardinal_preprocessing, cardinal_spectra_plots, rgrnastar from update 34

---

requests/mircounts.yml

tool request for mircounts

---

requests/fasta_extract__nml.yml

nml's wrapper of fasta_extract (adapted from simongladman's wrapper)

Install nml owned version of fasta_extract

---

requests/novoplasty.yml

For issue #346.  This is an IUC tool.

Install novoplasty

---

requests/cap3.yml

tool request for cap3

---

requests/cuffdiff.yml

latest version of cuffdiff

---

requests/bandage@94fe43e75ddc.yml

This hasn't gotten past staging because the env is broken on staging.  I have not been able to fix it.  I've installed this revision on staging so it will just skip the staging tests and move on to production where the env is OK.

retry bandage from update_41

---

requests/rgrnastar@7ed2edc1337f.yml

tool fails tests with data tables

[FORCE] rgrnastar from update_39

---

requests/peptideshaker@1beff3ddce58.yml

test failed because of minor diffs in decimals in output

[FORCE] peptideshaker from update_40

---

requests/bowtie_wrappers@latest.yml

test failed because of data tables

[FORCE] bowtie_wrappers from install_551

---

requests/find_subsequences@latest.yml

env did not install properly, should be ok now

retry find_subsequences from install_551

---

requests/chem_stats_transcriptomics_variant_analysis.yml

missing tools from statistics, computational chemistry, variant analysis and transcriptomics (except raceid tools)

Various missing GTN tools

---

requests/deeptools_plot_heatmap@010e58e9d822.yml
requests/gmx_sim@f197e34c33a9.yml
requests/peptideshaker@3634c90301af.yml
requests/peptideshaker@a72c48001f7c.yml
requests/query_tabular@1ea4e668bf73.yml

deeptools_plot_heatmap, gmx_sim, peptideshaker@3634c90301af, peptideshaker@a72c48001f7c, query_tabular from install_572
failed on minor numeric diffs, file sim size or data tables

[FORCE] some GTN smorgasboard tools

---

requests/miniasm@8b6d0d85252b.yml

There were test errors with 504 Galaxy under heavy load.  The tests should pass.

retry miniasm from install_572

---

requests/featurecounts@f3a5f075498f.yml
requests/pep_pointer@073a2965e3b2.yml
requests/rna_starsolo@ec9cbd6b9a49.yml
requests/unipept@34758ab8aaa4.yml

pep_pointer, featurecounts, rna_starsolo, unipept

[FORCE] smorgasboard 2

---

requests/pep_pointer@073a2965e3b2.yml
requests/rna_starsolo@ec9cbd6b9a49.yml
requests/unipept@34758ab8aaa4.yml

pep_pointer, rna_starsolo, unipept

[FORCE] smorgasboard 3

---

requests/snpeff_4_1.yml

user request for snpeff 4.1

---

requests/filtlong.yml

tool request filtlong

---

requests/proteomics_requests.yml

For tool requests
#405
#406 
#410 
#411

encyclopedia tools and uniprotxml_downloader

---

requests/openms_fraggeradapter.yml

openms_msfraggeradapter

---

requests/new_tools.yml

install parsnp

---

.ci/check_files.py
requests/tool_request_file.yml

user tool request: obi tools

---

requests/tool_request_file.yml

khmer tools to replace kmergenie

install khmer tools

---

requests/guppy.yml

user tool request for guppy

---

requests/exonerate.yml

user tool request for exonerate

---

requests/breseq@82fb5e3bb93e.yml
requests/kallisto_pseudo@01247aaf0a10.yml
requests/peptideshaker@07ff622ec007.yml
requests/snippy@fa016f1eea1a.yml

breseq, snippy, peptideshaker, kallisto_pseudo

[FORCE] some tools from update_51

---

requests/medaka.yml

user tool request medaka_consensus_pipeline

---

requests/dada2.yml

For issue #452 
dada2 tools as well as a data manager.  There are 8 tools but only one of them needs reference data.

user tool request dada2

---

.ci/check_files.py
requests/text_mining.yml

creates tool section 'Other Tools'.
EU puts these in a tool section called 'Other Tools'.  The toolshed category is 'Text Manipulation'

GTN text mining tutorial tools

---

requests/kraken2@e674066930b2.yml

This is on aarnet-dev and produces output and does not break when run with test data and the Minikraken db

[FORCE] kraken2

---

requests/encyclopedia_encyclopedia@d263296cd73e.yml
requests/encyclopedia_quantify@1c5cbf8f79ce.yml
requests/encyclopedia_walnut@d6a4dfdad269.yml

The test files are not in the toolshed because they are too large.  They are in the github repo.  The tests pass.

[FORCE] encyclopedia tools

---

requests/blastxml_to_gapped_gff3.yml

tool request blastxml_to_gapped_gff3

---

requests/ena_upload.yml

tool request: ena_upload

---

requests/genomescope.yml

tool request genomescope

---

requests/sklearn_build_pipeline@0c74d3164ac8.yml
requests/sklearn_ensemble@4ecc0ce9d0a2.yml
requests/sklearn_estimator_attributes@c9ddd20d25d0.yml
requests/sklearn_generalized_linear@913bf1c4c7bb.yml
requests/sklearn_nn_classifier@823ecc0bce45.yml
requests/sklearn_searchcv@a36a45cb96fa.yml
requests/sklearn_svm_classifier@14fa42b095c4.yml

sklearn_build_pipeline, sklearn_ensemble, sklearn_estimator_attributes, sklearn_generalized_linear, sklearn_nn_classifier, sklearn_searchcv, sklearn_svm_classifier from update_57

[FORCE] failing sklearn tools

---

requests/ivar_trim@cf65217ad61c.yml
requests/jbrowse@a6e57ff585c0.yml
requests/minimap2@037c6e54df11.yml

ivar_trim and minimap fail tests that use data tables.  jbrowse passes 9/10

[FORCE] jbrowse, ivar_trim, minimap2 from update_58

---

requests/circexplorer.yml

tool request: circexplorer

---

requests/hifiasm.yml

tool request: hifiasm

---

trusted_owners.yml

remove velvet and old versions of scanpy from skip list

take velvet off the skip list

---

requests/varscan_somatic@latest.yml

fails one test that needs reference data

[FORCE] varscan_somatic from install_720

---

requests/augustus.yml

tool request: augustus

---

requests/graphlan@8f62f666dcb6.yml
requests/humann_regroup_table@c409a495841f.yml
requests/humann_rename_table@d24841f5c3d2.yml
requests/metaphlan@b89b0765695d.yml
requests/minimap2@3f4d6399997b.yml
requests/pangolin@b6abccb1f25b.yml

tests failed due to reference data and exact diffs between image files

[FORCE] from install 725 (1)

---

requests/keras_train_and_eval@ead8f1822587.yml
requests/keras_train_and_eval@f1b9a42d6809.yml
requests/ml_visualization_ex@05143043ca13.yml
requests/ml_visualization_ex@4a229a7ad638.yml
requests/model_prediction@60c726f5cc5e.yml
requests/model_prediction@83228baae3c5.yml

tools that failed because of uploads failing for test input files of type 'zip'

[FORCE] from install 725 (2)

---

.ci/check_files.py
requests/species_abundance.yml

Add ecology tool sections 'Species abundance', 'Climate Analysis' to the tool panel

gtn ecology

---

.env
jenkins/install_tools.sh
jenkins/main.sh
jenkins/report.sh
jenkins/requirements.yml
jenkins/utils.sh

Have parameters in .env for GA-specific variables such as the github committer email.  Refactor main.sh to make the flow more linear.  Instead of exporting everything and running import_tools.sh as a separate script, import the functions to main and run everything from there.

Update jenkins bash scripts

---

trusted_owners.yml

add crs4 to trusted

---

requests/some_more_tools.yml

two RNA-seq tools

---

requests/gmx_energy.yml

Tool request: gmx_energy

---

requests/trycycler.yml

tool request: trycycler

---

requests/iwtomics_loadandplot.yml

this breaks in one of its tests but we can force it

iwtomics_loadandplot

---

jenkins/new_server_tools.sh

We want --install_tool_dependencies for things like krona_text.  Reduce sleep from 60s to 20s

update new_server_tools script

---

jenkins/new_server_tools.sh

typo, noticed this when I was showing Grace

set log header properly

---

requests/featurecounts@ce44c6f2ba38.yml
requests/kallisto_pseudo@87c11c05d238.yml
requests/kallisto_quant@c971db6f0fe5.yml
requests/rgrnastar@44959aa06aeb.yml

featurecounts, kallisto_pseudo, kallisto_quant, rgrnastar all failed data table tests

[FORCE] tools from update 65

---

requests/repeatmodeler.yml

tool request: repeatmodeler

---

requests/flye@e27815e82dd4.yml
requests/salmon@49121db48873.yml

flye runs out of memory (on slurm1) for 2/6 tests, salmon fails 1 test out of 9 (data tables)

[FORCE] flye, salmon from update_66

---

requests/jellyfish.yml

user tool request: jellyfish

---

requests/some_assemblers.yml

shasta, abyss, raven

---

.ci/check_files.py
requests/mimodd_aln.yml

tool request: mimodd_aln

---

requests/suite_scanpy_scripts_list.yml

tools from scanpy suite request

---

requests/berokka.yml

tool request: berokka

---

requests/infernal@c9e29ac5d099.yml
requests/metaphlan@ff8f55893e7d.yml
requests/sam_to_bam@1e69848b596f.yml
requests/samtools_view@350bbc5c2ffd.yml
requests/stringtie@258d696dbd7e.yml

sam_to_bam, samtools_view, stringtie (data tables)
infernal (tabs vs spaces in test output tabular file)
metaphlan (tbb need to be downgraded to 2020.2 in the conda env)

[FORCE] update 73 tools

---

requests/gff3_rebase.yml

requested by MT in the server channel

tool request: gff3_rebase

---

requests/metadegalaxy_phyloseq_deseq2.yml
trusted_owners.yml

also add qfabrepo to trusted_owners.yml

Update metadegalaxy deseq tool

---

requests/uniprot_xml.yml

tool request: uniprot_xml_downloader

---

requests/bcftools_stats@c636e58df612.yml
requests/ena_upload@e1b3b37aa69f.yml
requests/minimap2@6b1e195506a3.yml
requests/samtools_view@df20f1fd453f.yml
requests/trim_galore@cd7e644cae1d.yml

bcftools_stats, ena_upload, minimap2, samtools_view, trim_galore

[FORCE] tools from update 78

---

requests/trinotate.yml

new trinotate

---

jenkins/report.sh

Make a POST request to the News API of new "Galaxy Content" website to publish a tool update.

Test POST to news API

---

requests/diamond@f921014aba5a.yml
requests/featurecounts@38b6d12edc68.yml
requests/lastz@3e1ea2facca6.yml
requests/minimap2@c0c2d0941de8.yml
requests/quast@7594365c546b.yml
requests/stringtie@333a6e13b622.yml

diamond, featurecounts, lastz, minimap2, quast, stringtie
Quast has an issue with uploading test files for 2/6 tests.  The rest are failing the tests that use data tables.

[FORCE] tools from update 83

---

trusted_owners.yml

add rnateam to trusted owners

---

requests/alba.yml

tool request: albatradis

---

requests/cutesv

tool request: cutesv

---

requests/encyclopedia_searchtolib@latest.yml
requests/openms_targetedfileconverter@latest.yml

encyclopedia_searchtolib, openms_targetedfileconverter.  The test-data is too large for the toolshed but everything passes on dev

[FORCE] encyclopedia and openms tools

---

requests/bionano.yml

bionano_scaffold

---

requests/mascurca.yml

tool request: mascurca_simple

---

requests/minia.yml

tool request: minia

---

requests/repeat_masker.yml

tool request: repeat_masker

---

requests/get_orfs.yml

For issue #692 
TODO: check section label
Tests fail because some of the test output files are missing.

[FORCE] install get_orfs_or_cdss

---

requests/combine_metaphlan.yml

install combine_metaphlan2_humann2

---

requests/pycoqc.yml

For GTN.  My script goes through all of the workflow.ga files but it should probably be extracting tool ids from the tutorial.md files as well.

install pycoqc

---

requests/ena_upload@6f6537780379.yml
requests/freebayes@a7c9782130e8.yml
requests/picard@881d7645d1bf.yml

[FORCE] update_93 tools

---

requests/humann2.yml

For GTN. The virtual environment is preinstalled on staging and production.

install humann2

---

jenkins/report.sh

Prod URL for GMS is site.usegalaxy.org.au (live now)

Update report.sh with new GMS URL

---

requests/breseq@0d18a3ba2d1c.yml
requests/datamash_ops@419027d822d6.yml
requests/ivar_trim@9f978da6528a.yml
requests/quast@675488238c96.yml

ivar_trim, quast, breseq, datamash_ops

[FORCE] tools from update_99

---

requests/diamond@1e3323a44643.yml
requests/merqury@589078edd230.yml
requests/pear@b4c6f054210a.yml
requests/stacks2_procrad@b4bab607eb05.yml

pear, diamond, stacks2_procrad, merqury

[FORCE] tools from update_101

---

requests/maker-patch.yml

This is the same version as the previous revision

new revision of maker

---

requests/astral.yml

New tool by an unknown developer.
https://toolshed.g2.bx.psu.edu/view/padge/astral/66ebc4b19d6c

[needs review] tool request: astral

---

requests/mob_suite.yml

https://toolshed.g2.bx.psu.edu/view/nml/mob_suite/93ba63eaf394 (this is not a suite, it is a tool shed repository with two wrappers)

tool request: mob_suite

---

requests/bcftools_consensus@95c6f3f4c77f.yml
requests/bcftools_convert_to_vcf@ecc9192912b8.yml
requests/bcftools_csq@6c790a091c7c.yml
requests/bcftools_mpileup@37757ffb4c5f.yml
requests/bcftools_norm@48291658fdf6.yml
requests/bcftools_stats@4d3ce9dc1525.yml
requests/cactus_cactus@9422c5a87ee2.yml

bcftools tools that use data tables + cactus_cactus that ran out of memory in 1/4 tests

[FORCE] tools from update 117

---

requests/mash_sketch.yml

Install mash_sketch in addition to requested tool mash

add mash_sketch

---

requests/bcftools_consensus@d3081540d175.yml
requests/bcftools_convert_to_vcf@55c0e906c14c.yml
requests/bcftools_csq@ae68ceb4cca3.yml
requests/bcftools_mpileup@5660b21a0dbd.yml
requests/bcftools_norm@6deb4d549bc9.yml
requests/bcftools_stats@388983871932.yml
requests/pygenometracks@7dd841a32245.yml

These are the tools that failed due to data manager tests, good to go

[FORCE] tools from update_119

---

requests/requested_tools.yml

https://toolshed.g2.bx.psu.edu/view/iuc/integron_finder/1ae00120dd24
https://toolshed.g2.bx.psu.edu/view/brinkmanlab/islandpath/7cb1fb9b582e

Tool requests: integron_finder and islandpath

---

requests/cutadapt@135b80fb1ac2.yml
requests/picard@b502c227b5e6.yml
requests/rgrnastar@980d2a2e1180.yml
requests/stringtie@914cfcba0ec8.yml

rgrnastar (data tables), stringtie (data tables), cutadapt (minor diffs in 1 test out of 33), picard (data tables)

[FORCE] tools from update 123

---

requests/new_tools.yml

These need labels before this can be merged

Biohackathon tools

---

requests/new_tools.yml

3 iuc tools
https://toolshed.g2.bx.psu.edu/view/iuc/mitos2/624606f7c996
https://toolshed.g2.bx.psu.edu/view/iuc/mitobim/ea46115c7f1e
https://toolshed.g2.bx.psu.edu/view/iuc/getorganelle/8b330a577046

Green eyed tree frog tools

---

requests/chembl@latest.yml

This passed 6/8 tests earlier in the year so it was rejected by Jenkins.  I've reviewed the test errors (file sim size for one chembl test, lines in a slightly different order for one chembl_structure_pipeline test) and these look like ones we can safely ignore.

[FORCE] chembl from install_952

---

requests/funannotate_annotate@9f2455341fac.yml
requests/funannotate_compare@494f0bb4a993.yml
requests/funannotate_predict@7abc5f6dd595.yml
requests/maxquant@837224ad1694.yml
requests/pygenometracks@14e7c35f3d00.yml
requests/stringtie@ae618321f34a.yml

funannotate_annotate, funannotate_compare, funannotate_predict, pygenometracks, stringtie, maxquant

[FORCE] tools from update 134

---

requests/requests/hifiasm_meta@fa35f1106d3e.yml

https://github.com/usegalaxy-au/usegalaxy-au-tools/pull/876

Retry hifiasm_meta from update build 135

---

requests/ipa_hifi.yml

Request ipa_hifi

---

requests/protk_tools.yml

These tools were tested with Singularity on dev last year, but I never got around to requesting them once Singularity became available on prod.

request protk tools

---

trusted_owners.yml

There's an issue with the new revisions of bakta. We've been advised to wait before updating.

Block new bakta revisions for now

---

requests/alphafold2@d00e15139065.yml
requests/bedtools@589e7e57fd6d.yml
requests/featurecounts@a56fbe2d6ba7.yml
requests/getorganelle@06bcf65179fb.yml
requests/gffcompare@f99dd58de04f.yml
requests/ivar_trim@bcaa0d571ce2.yml
requests/rgrnastar@4df95e2d7f61.yml
requests/rna_starsolo@1cd2511a396e.yml

alphafold2, bedtools, featurecounts, getorganelle, gffcompare, ivar_trim, rgrnastar, rna_starsolo

[FORCE] tools from update 138

---

requests/featurecounts@6f66ae7c5f7a.yml
requests/humann@2cd76b089570.yml
requests/humann_regroup_table@79706f10d680.yml
requests/humann_rename_table@172920f67a84.yml
requests/mitos2@033755194fe9.yml
requests/quast@72472698a2df.yml

humann, featurecounts, humann_rename_table, humann_regroup_table, mitos2, quast

[FORCE] tools from update 139

---

requests/metaphlan@2131d7dca455.yml
requests/rgrnastar@c7c55b694974.yml
requests/rna_starsolo@b8f5f6e87f5c.yml

metaphlan, rna_starsolo, rgrnastar

[FORCE] tools from update_141

---

requests/new_tools.yml

https://toolshed.g2.bx.psu.edu/view/iuc/star_fusion/137942fac417

tool request: star_fusion

---

requests/music_compare.yml

Please add this tool - the other MuSiC tools are already available so it would be good to have this one too.

Add MuSiC Compare tool

---

requests/alphafold2@f9eb041c518c.yml
requests/busco@94170eee0ad8.yml
requests/circos@c4bde687c846.yml
requests/dexseq@df929f257179.yml
requests/ivar_trim@28e4bcbc86e7.yml
requests/pygenometracks@360df4999907.yml
requests/rgrnastar@3ea5a2a63fa2.yml
requests/rna_starsolo@13022c3d3076.yml

busco, alphafold2, circos, dexseq, ivar_trim, pygenometracks, rgrnastar, rna_starsolo

[FORCE] tools from update 146

---

requests/funannotate_annotate@582fd74dc2a1.yml
requests/funannotate_compare@30f08d74024f.yml
requests/funannotate_predict@f31125bb85ea.yml
requests/humann@95bf7479d53c.yml
requests/humann_regroup_table@31c6d107e7a5.yml
requests/humann_rename_table@714d5a28cc5c.yml
requests/interproscan@74810db257cc.yml
requests/metaphlan@1a6cdf55390f.yml
requests/minimap2@be1d967337e4.yml

funannotate_annotate, funannotate_compare, funannotate_predict, humann, humann_regroup_table, humann_rename_table, interproscan, metaphlan, minimap2

[FORCE]  tools from update 147

---

requests/alphafold2@5b85006245f3.yml
requests/cutadapt@8c0175e03cee.yml
requests/getorganelle@611219887a48.yml
requests/kallisto_pseudo@ce5d418183c5.yml
requests/kallisto_quant@4f9c4e6566e5.yml
requests/pygenometracks@59fd173ac850.yml

alphafold2, cutadapt, getorganelle, kallisto_pseudo, kallisto_quant, pygenometracks

[FORCE] tools from update 153

---

requests/eirene.yaml

This PR adds a file for the tools for mass spectrometry data processing developed by RECETOX within EIRENE.

Added initial EIRENE tools from RECETOX

---

requests/cactus_cactus@9eeb13a92d79.yml
requests/dada2_assigntaxonomyaddspecies@76d3d2b10738.yml
requests/deeptools_plot_heatmap@25d830337d31.yml
requests/deseq2@9a882d108833.yml
requests/lastz@37b497aa133f.yml
requests/salmon@15cd64d7c58b.yml
requests/uniprotxml_downloader@a371252a2cf6.yml

cactus_cactus, dada2_assigntaxonomyaddspecies, deeptools_plot_heatmap, deseq2, lastz, salmon, uniprotxml_downloader
All failed for reasons such as ref data and sim size comparison

[FORCE] tools from update 157

---

requests/tools_q2d2.yaml

Just updated the tool name from qiime2__deblur__denoise_16S to qiime2__deblur__denoise_16s

Qiime2 rebase

---

requests/ena_new.yml

This will fail at least one test, can compare to previous results on staging then '[FORCE]' and skip tests

tool request: latest ena_upload

---

requests/alphafold2@e4a053d67e24.yml
requests/arriba@01ccd366690d.yml
requests/bwa_mem2@bfaa0d22c2e4.yml
requests/dada2_assigntaxonomyaddspecies@7c2100246a2f.yml
requests/deeptools_plot_correlation@bad3ca889618.yml
requests/featurecounts@f9d49f5cb597.yml
requests/funannotate_annotate@b6b5cd37f2a2.yml
requests/funannotate_compare@5a5ae61da69c.yml
requests/funannotate_predict@d6c7106b7b2e.yml
requests/ncbi_blast_plus@a52d2d93e595.yml
requests/rgrnastar@79de45b5069b.yml
requests/rna_starsolo@5ef7ec16b04f.yml
requests/sortmerna@10b84b577117.yml

alphafold2, arriba, bwa_mem2, dada2_assigntaxonomyaddspecies, deeptools_plot_correlation, funannotate_annotate, funannotate_compare, funannotate_predict, featurecounts, ncbi_blast_plus, rgrnastar, rna_starsolo, sortmerna

[FORCE] tools from update 170

---

requests/template/seq_filter_by_id.yml

For ticket https://dhdnectar.freshdesk.com/a/tickets/190552
Upstream issue: https://github.com/peterjc/pico_galaxy/issues/39

Bump seq_filter_by_id to 0.2.8

---

requests/new_braker.yml

[FORCE] latest braker3

---

requests/busco@2a5b8b9936bf.yml
requests/chipseeker@8bd92f2404dd.yml
requests/funannotate_annotate@756376aeb1ae.yml
requests/funannotate_compare@e94187d661df.yml
requests/humann_rename_table@094ad9c068af.yml
requests/merqury@09c589057ee8.yml
requests/samtools_view@6be888be75f9.yml
requests/scanpy_filter@a03ff8633507.yml
requests/scanpy_normalize@94c19fb1281c.yml

busco, chipseeker, funannotate_annotate, funannotate_compare,humann_rename_table, merqury, samtools_view, scanpy_filter, scanpy_normalize

[FORCE] tools from update 175

---

requests/funannotate_annotate@3bbe70fef6df.yml

I think we're missing 2 revisions of this tool because the tests fail. I've tested this revision with planemo locally

[FORCE] Update funannotate_annotate

---

requests/anndata_inspect@6f0d0c784f09.yml
requests/funannotate_compare@b69c46064ec7.yml
requests/funannotate_predict@f77d7b685bb3.yml
requests/humann@fc6c328c292f.yml
requests/ncbi_blast_plus@d999e774072a.yml

anndata_inspect, funannotate_compare, funannotate_predict, humann, ncbi_blast_plus

[FORCE] tools from update 176

---

requests/pharokka.yml

Closes https://support.ehelp.edu.au/a/tickets/192961

Install pharokka

---

requests/mmpbsa.yml

tool request: mmpbsa_mmgbsa

---

requests/cactus_export@latest.yml

From https://github.com/usegalaxy-au/usegalaxy-au-tools/pull/1043

Retry cactus_export

---

requests/cactus_cactus@latest.yml
requests/cactus_export@latest.yml
requests/funannotate_annotate@latest.yml

These are failing on staging. cactus_cactus passed on prod. The other two weren't tested there.

[FORCE] cactus and funannotate

---

requests/bakta@92eee5f31117.yml
requests/metaphlan@fd69c607b43f.yml
requests/mitos2@b815ec682418.yml

[FORCE] tools from update_182

---

requests/anndata_ops.yml

As requested by Sarah: https://support.ehelp.edu.au/a/tickets/190760

Update anndata ops version

---

requests/integron_finder@392f100eebcd.yml
requests/kraken_taxonomy_report@bfae8da6082c.yml
requests/mummer_delta_filter@e8fdceffea4c.yml
requests/mummer_mummer@57f042937ba7.yml
requests/picard@3f254c5ced1d.yml
requests/salmon@f4d5237a84f6.yml

mummer_mummer, mummer_delta_filter, integron_finder, kraken_taxonomy_report, picard, salmon

[FORCE] tools from update 187

---

requests/alphafold2@2f7702fd0a4c.yml
requests/cutadapt@b1c926deaa2d.yml
requests/getorganelle@ba88bc5a6446.yml
requests/metaphlan@289b3807e80c.yml
requests/mitos2@c8ac28e8ac44.yml
requests/ncbi_blast_plus@cbf3f518b668.yml
requests/scanpy_filter@277313130da5.yml
requests/spades_plasmidspades@8cc856b935ee.yml
requests/stringtie@cbf488da3b2c.yml

alphafold2, cutadapt, getorganelle, ncbi_blast_plus, mitos2,metaphlan, stringtie, scanpy_filter, spades_plasmidspades

[FORCE] tools from update 194

---

requests/dorado.yaml

Wait until the local_tools version is removed: https://github.com/usegalaxy-au/infrastructure/pull/2043
The dorado tests will fail unless we can get it to run on GPU.

[FORCE] request toolshed dorado

---

requests/new_request.yml

lotus2 and biopdb_align_and_rmsd, pending tpv entries

new tools requests

---

requests/template/agat.yaml

`Another Gtf/Gff Analysis Toolkit` for various GFF/GTF conversions

Request AGAT

---

requests/single_cell_lab_filtered.yml

I think this is what remains after filtering already installed tools

Install remaining single-cell tools

---

trusted_owners.yml

tool test jobs go into paused state which stops the update process until the jobs are manually failed

add qualimap_rnaseq to skip list

---

requests/bedtools@64e2edfe7a2c.yml
requests/bracken@0c7b6eb7e752.yml
requests/cpat@7ccc6234b54e.yml
requests/cutadapt@5eb7e84243f2.yml
requests/dada2_assigntaxonomyaddspecies@65db807336bc.yml
requests/integron_finder@bfd290fe1588.yml
requests/ivar_trim@a250929be21b.yml
requests/kraken2@cdee7158adf3.yml
requests/minimap2@5cc34c3f440d.yml
requests/uniprot_rest_interface@468c71dac78a.yml

bracken, bedtools, cpat, cutadapt, integron_finder, ivar_trim, dada2_assigntaxonomyaddspecies, kraken2, minimap2, uniprot_rest_interface

[FORCE] tools from update 203

---

requests/ragoo.yml

For Anna
https://support.ehelp.edu.au/helpdesk/tickets/210315

Request Ragoo installation

---

requests/bbtools.yml

Requesting BBTools that are on EU but not AU (for @mthang )

Request missing BBTools

---

requests/template/gta2024_microGalaxy.yml

We would need this specific version for the GTA.
Not sure if `tool_panel_section_label: Metagenomics` is correct ?

[FORCE] Add metaphlan v4.0.6+galaxy0

---

requests/filesender.yml

After https://github.com/usegalaxy-au/infrastructure/pull/2195.
Also, I'm hoping we can use apptainer once the mulled container gets built: https://github.com/BioContainers/multi-package-containers/pull/3353

filesender

---

requests/falco.yml

This is apparently like fastqc but better

install falco

---

requests/featurecounts@5dbff3a5845a.yml
requests/infernal@3711f654044e.yml
requests/quast@a3b35edea53a.yml

quast, infernal and featurecounts

[FORCE] tools from update_228

---

requests/arriba@6535dd4a4064.yml
requests/bakta@1942e86e2ee1.yml
requests/bwa_mem2@bec6ba059ded.yml
requests/cutesv@ccc439243918.yml
requests/dorado@5e67ea368004.yml
requests/ncbi_blast_plus@fc35ffc8c548.yml
requests/ncbi_fcs_gx@2559b7ce2114.yml
requests/recentrifuge@cfb53a01abc5.yml

arriba, bakta, bwa_mem2, cutesv, dorado, ncbi_blast_plus, ncbi_fcs_gx, recentrifuge

[FORCE] tools from update 241

---

requests/decoupler.yml
usegalaxy.org.au/hca_single_cell.yml

add decoupler

---

requests/coverm.yml
usegalaxy.org.au/metagenomic_analysis.yml

Add CoverM Tools needed for a GNT for the GTA

Add CoverM Tools for GTA

---

requests/arriba@0da0b2dc624c.yml
requests/canu@e05f5ee0ffb9.yml
requests/waveica@821062fc5782.yml

[FORCE]  from update_264

---

requests/helixer_update.yml

Hi!
I'm trying to request helixer wrapper 0.3.3 from toolshed, I hope I got the format correct. Current version is 0.3.2.
Thanks!

[FORCE] Request helixer update
