usegalaxy-au/usegalaxy-au-tools

jenkins/install_tools.sh
jenkins/main.sh

Jenkins runs this code in two contexts: requested via PR and weekly tool updates.  Builds from both contexts have integer build numbers.  Rename log files and jenkins commits to include 'install', 'update' so they unique.

Differetiate between "install" and "update" jenkins builds

---

automated_tool_installation_log.tsv
jenkins/install_tools.sh
jenkins/main.sh
jenkins/report.sh
jenkins/requirements.txt
scripts/is_tool_new.py
scripts/organise_request_files.py
scripts/write_report_from_log.py

Automatically generate a report of added/updated tools for the website after the update script is run (each Tuesday)
There is a sample report here:
https://github.com/jenkins-bro/website/blob/jenkins/2020-03-02_tool_updates/_posts/2020-03-02_tool_updates.md
Also:
-  When running the automatic install from a pull request, run a script to differentiate between new tools and updates of existing tools.
-  Rearrange log tsv file so that the tool name is visible in the github view without having to scroll right
-  For the weekly update, filter the trusted tools so that only those without the latest installable revision installed go through the install process
-  Better organisation of python requirements for the jenkins process.

Automatically generate report after each update

---

jenkins/install_tools.sh

Currently, if a tool is installed without specified revisions, the test step is running every available test for the tool rather than only those for the revision that is installed.  This might be blocking some new revisions that would pass the tests on their own.

ensure that only relevant tests are run during jenkins tool installation

---

jenkins/install_tools.sh
scripts/is_tool_new.py
scripts/wait_for_tool.py

On a jenkins job (update 5), tests were running on staging before the (job/web?) handlers were aware of the tools existence, so no tests were run on staging.  This will repeatedly check whether the tool in the list of all repos waiting 30 seconds between tries.  Run this just before testing instead of 'sleep 30'

script to wait until galaxy is aware of new tool

---

requests/bedtools@latest.yml
requests/jbrowse@latest.yml
requests/lofreq_call@latest.yml

These 3 tools failed the update process.  The errors seem to be ones we can safely ignore
(1) bedtools (100/103) failed 3 tests with 'History item different from expected', no log of the diff in the test.json
(2) jbrowse (9/10) failed 1 test with 'History item different from expected',
```
( /tmp/tmpkkL9D4test.xml v. /tmp/tmpS12wITtest.xml )
--- local_file
+++ history_data
@@ -3,15 +3,15 @@
<metadata>
<gencode>11</gencode>
<genomes>
-              <genome path="/tmp/tmpqkd9zdgq/files/b/f/a/dataset_bfad32fe-cc05-405c-965c-6fe9b7a36908.dat">
-                <metadata>
-                  <dataset id="b842d972534ccb3e" hid="1"
+              <genome path="/mnt/galaxy/files/000/522/dataset_522278.dat">
+                <metadata>
+                  <dataset id="1fd3433eb76c5b63" hid="3" …
```

[FORCE] Update lofreq_call, jbrowse and bedtools

---

requests/bcftools_consensus@latest.yml
requests/bcftools_convert_to_vcf@latest.yml
requests/bcftools_stats@latest.yml
requests/fasta_compute_length@latest.yml
requests/gemini_load@latest.yml
requests/kallisto_pseudo@latest.yml
requests/kraken@latest.yml
requests/rgrnastar@latest.yml
requests/snippy@latest.yml
requests/stringtie@latest.yml

Tests that come with their own test data tables will not pass automated tests according to https://planemo.readthedocs.io/en/latest/writing_how_do_i.html#test-index-loc-data
These tools are only failing the tests that depend on data tables.
bcftools_consensus (2/3)
bcftools_convert_to_vcf (5/7)
bcftools_stats (2/3)
fasta_compute_length (3/5)
gemini_load (0/5)
kallisto_pseudo (4/5)
kraken (0/2)
rgrnastar (9/11)
snippy (7/9)
stringtie (11/12)

[FORCE] install tools from update 8 that failed due to test data tables

---

jenkins/main.sh
scripts/is_tool_new.py
scripts/organise_request_files.py

Jenkins has been trying to update kraken_filter which is deactivated on galaxy.  Add a check to prevent update of tools that are not active.
Change method for deciding whether to update
(Hopefully) fix check for whether a tool is new or not.

add check for repository status when updating

---

jenkins/install_tools.sh

Instead of passing the installed revision hash to `shed-tools test`, allow it to run all tests for an updated tool.  The reason for this is that if a new revision has been added but the tool version is the same, the tool panel will remain unchanged and shed-tools will not be able to locate tests for the new revision hash.

revert to running all tests for updates

---

requests/scrna_versions.yml

Usually a workflow can be run on Galaxy if we have the tool of any version.  If the workflow contains subworkflows, the algorithm that loads subworkflow steps will raise an exception for any tool version mismatch, and the workflow cannot be loaded.

specific tool versions for tutorial Pre-processing of Single-Cell RNA

---

requests/abricate@latest.yml
requests/fastp@latest.yml
requests/ivar_trim@latest.yml

- abricate failed due to filepaths being on pulsar but passed everything on staging
- fastp passed 10/11, failed one due to unexpected file extension (expected [fastqsanger] but found [fastq])
- ivar_trim passed 3/4, failed one due to the test using test data tables

[FORCE] install tools abricate, ivar_trim, fastp (failed in update_12)

---

requests/jbrowse@latest.yml

Passes 9/10 tests, one fails because of filepaths in the history file, the previous revision was force-installed for the same reason

[FORCE] install tool jbrowse

---

.travis/check_files.py
jenkins/install_tools.sh
jenkins/main.sh
jenkins/requirements.yml
scripts/organise_request_files.py
trusted_owners.yml

The organise_request_files.py that checks for new revisions also does a version check now.  If a new revision comes without a version bump we cannot test it in shed-tools and we must not uninstall it because we would remove an existing version (https://github.com/usegalaxy-au/usegalaxy-au-tools/issues/157).  The output request file for the tool has `# [SKIP_TESTS]` prepended.
trusted_tools.yml has been altered slightly to allow a specific revision of a tool to be blacklisted.
Including pysam in jenkins requirements means that some test that previously failed will pass.  There are 3 jenkins jobs using exactly the same .venv setup so this is being moved to ~/jobs_common.  It doesn’t matter if this gets wiped out in a jenkins update, the script will recreate it.

update organise_request_files, trusted_owners, use common virtualenv for Jenkins jobs

---

.travis/check_files.py
jenkins/install_tools.sh
jenkins/report.sh

The tools with [SKIP_TESTS] were not being logged in the update ... this will fix that.  The entries for the .tsv file have been stored in memory which is a bad idea if the script ever has to be stopped in the middle.

Save installation log as a temporary file, make sure SKIP_TESTS and FORCE follow the same logic

---

trusted_owners.yml

This revision of deeptools_bam_pe_fragmentsize fails tests because it depends on the wrong version of matplotlib.  They have already fixed this in the development repo and there will probably be a new revision soon

blacklist deeptools_bam_pe_fragmentsize

---

requests/dropletutils@latest.yml
requests/goenrichment@latest.yml

dropletutils fails tests that compare .png files that look identical, might be some differences in font size of plot labels
goenrichment fails diff because output has '1.94e-5' instead of '1.94E-5'

[FORCE] install tools dropletutils, goenrichment (failed in install 284)

---

requests/blockclust@latest.yml
requests/pathview@latest.yml

pathview failed to install while Galaxy was under heavy load, blockclust had a strange test failure on production where blockclust.py couldn't be found

retry tools blockclust, pathview (failed in install_284)

---

requests/bp_genbank2gff3@11c3eb512633.yml
requests/cat_bins@18676df0cb3a.yml
requests/data_manager_gemini_database_downloader@5bcf0e24f42c.yml
requests/scanpy_cluster_reduce_dimension@b2df381a6004.yml

- bp_genbank2gff3 should have passed, failed on uploads of test data with gateway timeouts
- data_manager_gemini_database_downloader cannot be tested with shed-tools
- cat_bins cannot be tested (all tests use data tables)
- scanpy_cluster_reduce_dimension fails one test on an optional dependency (passes 9/10 tests)

[FORCE] install some tools from update 18

---

requests/sequence-analysis.yml

The workflows will run with the versions on GA but the specific tool versions from the workflows are needed in order to be able to load and test them through the API.

more tools for sequence-analysis tutorials

---

trusted_owners.yml

diffbind and raxml because they are repeatedly installed on production and uninstalled due to breaking tests, gemini tools because we don't want these installed ahead of database needs they might have

blacklist diffbind and raxml current revisions and all gemini tools

---

jenkins/install_tools.sh
jenkins/main.sh
scripts/first_match_regex.py
scripts/organise_request_files.py
scripts/uninstall_tools.py

- Revert to continuing installation if tool has no tests
- Update uninstall_tools.py to use bioblend instead of ephemeris
- Replace SKIP_TESTS value coming in from organise_request_files.py with VERSION_UPDATE. This is used so that jenkins knows not only to skip tests, but to not uninstall the tool under any circumstances.
- Reduce pre-test sleep to 90 seconds.
- Get rid of the bash version check, just use the python helper instead of bash regex

Revert to continuing installation if tool has no tests

---

requests/ivar_trim@5d6ed46cc101.yml
requests/lofreq_call@074d44697036.yml
requests/minimap2@8c6cd2650d1f.yml
requests/peptideshaker@7fdd9119cc4f.yml

- minimap2 failed due to test data tables
- ivar_trim failed due to test data tables
- peptide shaker failed due the compared output file containing file paths
- lofreq_call has one test where the output is different to what is expected.  In this case it looks like the test-data expected VCF file might be incorrect.  The test output is like the expected output but with more fields in the INFO column (subset pasted below)
```
- expected test output
+ test output
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
-pBR322	725	.	G	GN	0	.	;HRUN=1
-pBR322	746	.	A	AN	0	.	;HRUN=1
+pBR322	725	.	G	GN	0	.	DP=46;AF=0.021739;SB=0;DP4=22,23,0,1;INDEL;HRUN=1
+pBR322	746	.	A	AN	0	.	DP=225;AF=0.004444;SB=3;DP4=116,108,0,1;INDEL;HRUN=1
```

[FORCE] install some tools that failed update 20 + Peptide Shaker

---

trusted_owners.yml

Jenkins tried to update this last week but the tests failed because a data type sra_manifest.tabular does not exist pre-20.05.

skip sra_tools until the data type is available (20.05)

---

requests/proteomics_tutorial_few.yml

The versions of these tools failed (install 311) tests due to python errors but have more recent versions available

3 proteomics tutorial tools

---

trusted_owners.yml

There are errors in the tool tests either due to either the code or the test input data.   I'll look into this after BCC.  Also blocking all revisions (not just a specific one) of sra_tools until 20.05

Add scanpy_plot and scanpy_inspect to the skip list

---

requests/older_mothur_sub_sample.yml

There are known issues with the version of this tool on GA.  Igor has tested the older version on Galaxy Europe and it works.

Install version 1.36.1.0 of mothur_sub_sample

---

trusted_owners.yml

Tool destinations has been updated to send jobs with very small inputs to slurm1 - we can see how it goes in tomorrow's update

remove raxml from skip_tools list

---

jenkins/requirements.yml

h5py is imported in the galaxy-tool-util testing in the same way as pysam:
```
try:
import h5py
except ImportError:
h5py = None
```

Jenkins venv needs h5py for some tests

---

requests/sra_tools@653e89d73fc4.yml

This passes tests except for the ones that use a datatype that is not on staging.  Tests can be run on production post install to make sure it is good

[FORCE] sra_tools from update_30

---

requests/fasta_merge_files_and_filter_unique_sequences@650d553c1fda.yml
requests/velvet@8d09f8be269e.yml

- fasta_merge_files_and_filter_unique_sequences fails its test because of a newline at the end of the output file
- velvet fails output diffs on production but this can pass because is is a training-only tool

[FORCE] fasta_merge_files_and_filter_unique_sequences, velvet

---

jenkins/report.sh
jenkins/requirements.yml
jenkins/update_tool_panel_labels.sh
scripts/update_tool_panel_labels.py
scripts/utils.py
tool_panel/tool_labels.yml

Jenkins script to copy shed_tool_conf.xml and label tools as 'new' or 'updated' if they have been installed in the past 14 days.  Other tool labels are defined in tool_panel/tool_labels.yml (deprecated, training-only).
This uses methods from galaxy-util for parsing and writing xml, so comments are preserved and the resulting file is like the original but for the labels.
The labels have been added to the tool panel on staging.

Update tool labels in panel

---

requests/data_manager_bwameth_index_builder.yml

Tools were recently added for Epigenetics tutorials.  One of the tutorials cannot be run yet because there is no reference data for bwameth

data manager for bwameth

---

jenkins/simple_install_test.sh

Script to install and test from a single .yml file.
Usage:
```
export URL=https://staging.usegalaxy.org.au
export LOG_DIR=~/new_staging_tools
bash simple_install_test.sh usegalaxy.org.au/annotation.yml
```
The jenkins_bot api key for staging will be set from Jenkins.  This could be set to loop through all of the .yml files in usegalaxy.org.au or just install one at a time.  I'd like to try with just one to start with.  This can be marked as ready to merge when it has been tested on galaxy-cat.

very simple installation script for new staging

---

jenkins/install_tools.sh

Some of the uninstall requests fail because Galaxy is under heavy load.  This may help.

galaxy-wait before winding back installation

---

jenkins/requirements.yml

This clashes with what ephemeris requires

Drop galaxy-util from jenkins requirements

---

jenkins/new_server_tools.sh
jenkins/requirements.yml

There have been issues with tool installations on the new staging server.  This is a variation of the install_tools.sh script that runs shed_tools install on each tool one by one then runs tests.  Unlike that process, this does not uninstall tools that have failed tests.  It does still uninstall tools with API errors or timeouts.  On the new staging there are issues with running `conda create` processes accumulating to the point that the server is too busy for the shed-tools API calls.  Since these processes should not be running between installations, this script will kill running `conda create` processes when it runs into errors.

Jenkins new_server_tool.sh script

---

trusted_owners.yml

Openms tools need to be tested independently
The new version of unicycler will not install until we are on galaxy 20.09 (although ephemeris will think it has installed)

no auto-update of openms because they have tests and no test data

---

requests/gtn_proteomics.yml

GTN proteomics tools that we don't have, excluding msconvert (requires proteowizard on system) and unique by bgruening (it looks like this was absorbed into the galaxy code base so we already have it).
A few of these are tools that we have tried to install in the past without success, but it's worth trying again.  Some of them will be from new or revised tutorial workflows.

GTN proteomics tools

---

requests/gtn_genome_annotation.yml

This includes devteam's `bowtie_wrappers` which is actually bowtie1
Also a new version of maker.  This one might run on slurm, the old one wouldn't.
jcvi_gff_stats is excluded from the list because has timed out with previous install attempts.

GTN genome_annotation tools

---

requests/translate_bed.yml

From the GTN smorgasboard list
The version of biopython that this requires (1.62) is not in conda and the environment will fail to install.  It passes its tests on staging with biopython 1.70 instead

[FORCE] install translate bed skipping conda install

---

requests/seq_filter_by_id.yml

Needed for 'Understanding Barcodes' tutorial on Wednesday.
This works on dev but cannot be tested because the test data is missing from the repo.

[FORCE] seq_filter_by_id

---

requests/msstats.yml

Thursday's maxquant tutorial has just been merged into GTN.  GA has all of the tools except for this one.

msstats for new maxquant tutorial

---

jenkins/install_tools.sh

the really long diff is annoying when reading the logs on jenkins and it doesn't seem that useful

leave git diff of changes out of jenkins log

---

requests/phyml.yml

We have phyml by vlefort from 2016.  iuc has since taken it over, this version is from 2020

iuc version of phyml

---

jenkins/install_tools.sh

This might be good to put this in ahead of GTN requests.  The current code puts the onus on the requester to have `install_tool_dependencies: true` in the yaml file but it's difficult to reinstall (because of repository dependencies that remain installed) if we find that we needed it.  It shouldn't have any effect on tools that do not have a legacy requirements.xml file.

install tool dependencies always with shed-tools install

---

scripts/is_tool_new.py
scripts/organise_request_files.py
scripts/uninstall_tools.py

Update organise_request_files check for version updates.  The old method was correct most of the time but would have been skipping tests more often than it needed to.  Make fewer calls to the 'get_repository_revision_install_info' endpoint.  Update some bioblend imports.

Update organise_request_files and import fewer bioblend clients

---

requests/ncbi_sarf.yml

the revision hashes might be wrong for these (ie not the installable revisions) but the linter will check

tools for ncbi-sarf tut

---

requests/jcvi.yml

The environment needs to be installed by hand so skip testing

[FORCE] jcvi_gff_stats

---

requests/dada2_assigntaxonomyaddspecies@63f86089423e.yml
requests/genomescope@3169a38c2656.yml
requests/humann_rename_table@71ea608ddfa3.yml
requests/maxquant@e42225f8a659.yml
requests/metaphlan@a92a632c4d9b.yml
requests/minimap2@09b53c1d4ab1.yml
requests/query_tabular@623f3eb7aa48.yml
requests/snippy@d220115f882b.yml

maxquant has barely noticeable diffs in one of its output files for 1/8 tests, genomescope tests can't pass because they compare image files with exact diff, the rest have failed tests that use data tables.

[FORCE] some tools from update 64

---

requests/rna_starsolo@a6fba3d92531.yml

Tests are failing when the tests are run in parallel and passing when they are run one by one.  This is probably a bug in galaxy-tool-util because the test jobs are using the same input datasets even though the datasets are uploaded separately for each job.

[FORCE] rna_starsolo from update_64

---

jenkins/requirements.yml

There's a change in 0.10.7 that strips the tool version from the tool id and it breaks testing for older tools, it means that it always downloads test-data files for the most recent version.
Also anchor galaxy-tool-util version and remove pysam and bioblend dependencies that are satisfied by installing ephemeris.

Update jenkins requirements to add another ephemeris patch

---

requests/merqury@9d79beb19ac3.yml
requests/meryl@51c2360aa807.yml

meryl fails sim size tests
merqury tests cannot run because of mistakes in the test xml in the wrapper.  I'm working on corrections for this but it might take a while.  The tool can definitely run and produce output.

[FORCE] meryl, merqury from install_793

---

requests/humann.yml

For issue #562 and for GTN
The environment has been built in advance on staging and pawsey.  This will fail tests because of tests that use reference data but if it passes 1/6 on staging then it is working and can be force installed

install humann

---

requests/cardinal_data_exporter@be5d1c3c51e5.yml
requests/cardinal_filtering@105056844497.yml
requests/cardinal_preprocessing@accf9fb6ea01.yml
requests/cardinal_quality_report@23d0394b5908.yml
requests/cardinal_segmentations@5279bc051339.yml
requests/cardinal_spectra_plots@d333733dd571.yml
requests/ivar_trim@c092052ed673.yml
requests/meryl@5ae3496f9ca3.yml

cardinal tools pass their tests when not run in parallel
meryl has file size diffs, same as when it was installed
ivar_trim has data table tests

[FORCE] update 70 tools

---

requests/canu@86f150c8019d.yml
requests/maxquant@97a7f34fcb6a.yml

canu fails tests on production with a message that there is not enough memory.  It passes the same tests on staging, probably because the slurm settings have not been updated there.
maxquant fails every week on staging with a test that passes on dev, no idea why... I think it's worth just installing this update.

[FORCE] canu, maxquant from update_79

---

jenkins/install_tools.sh

Increase the waiting time before running tests to 90 seconds because last week some of the tool tests were not found.

set jenkins sleep before testing to 90 seconds

---

requests/cuffdiff.yml

GA used to have cuffdiff but lost it in the move to pawsey because the environment would not resolve.
For issue https://github.com/usegalaxy-au/usegalaxy-au-tools/issues/360

install cuffdiff again

---

jenkins/report.sh

Since GMS was updated to serve over HTTPS it just returns a redirect when posting to HTTP.
This has been fixed.

POST tool updates to GMS over HTTPS

---

requests/metaphlan2.yml

the environment for this is `mulled-v1-c5867e29ea0fba532ec8dc4a557d8798445dccb6ecf21f67e09143751a79b65d` and has been created on staging and production with `metaphlan2=2.6.0 bowtie2=2.3.0 python=2.7.15 tbb=2020.2`.  The tool wrapper asks for `metaphlan2=2.6.0 bowtie2=2.3.0 python=2.7.10`.  python 2.7.10 is no longer in conda, the earliest is 2.7.12.

tool request: metaphlan2

---

requests/annotation.yml
requests/template/annotation.yml

Adding tools for the [Funannotate GTN tutorial](https://training.galaxyproject.org/training-material/topics/genome-annotation/tutorials/funannotate/tutorial.html)
There will be some data managers to run afterwards, and possibly [licensed components to install/configure for interproscan](https://github.com/galaxyproject/tools-iuc/blob/master/tools/interproscan/README.md#installing-licensed-components-manually) if you want to make them available (not mandatory)

Add tools for Funannotate tutorial

---

requests/ncbi_blast_plus@0e3cf9594bb7.yml

Checked on dev.  Non-ref-data tests will pass if the test-data folder is moved to the same dir as the wrappers.

[FORCE] newest ncbi_blast_plus

---

requests/antismash@bc88856eddab.yml
requests/bowtie2@f6877ad76b00.yml
requests/column_maker@6595517c2dd8.yml
requests/lofreq_alnqual@791f73caa0c8.yml
requests/metabat2@708abf08a626.yml
requests/pangolin@77402759b866.yml
requests/rnaspades@378e55aeeb25.yml

retry antismash, bowtie2, metabat2, lofreq_alnqual, column_maker, rnaspades from update_110
All of these tools failed their tests on production because the tests were being set up before the handlers had updated.  The timeout between installing and updating has since been increased.

Retry updating some tools

---

requests/bcftools_mpileup@f506df85c652.yml
requests/ena_upload@d147d6455873.yml
requests/ivar_trim@5671e1d3d5ee.yml
requests/meryl@29dabd8db6f2.yml
requests/metaspades@606b09cc9860.yml
requests/raxml@29ff6a849eac.yml
requests/spades@78ced22d09a2.yml
requests/spades_plasmidspades@6aad515a5270.yml
requests/spades_rnaviralspades@b3490b036c5a.yml

Tools that fail ref data tests: bcftools_mpileup, ivar_trim
Tools that routinely fail a couple of tests with minor differences in output size: meryl, metaspades, raxml, spades, spades_plasmidspades, spades_rnaviralspades, ena_upload

[FORCE] tools from update 110

---

jenkins/install_tools.sh

With tools that run with singularity containers, the first job run will download from quay.io and build the sif file in /mnt/tools/cache/singularity.  If jobs are running in parallel, they are all trying to do this and it can result in the jobs failing and/or failing to build the sif file.
Also reduce the sleep from 180 to 60 seconds.

Remove --parallel_tests from test command

---

requests/bcftools_mpileup@31ea13dfe5e6.yml

This failed last week because one of the tests uses test data tables.  I'm going to merge this straight away to check that Jenkins is working correctly after the update

[FORCE] bcftools_mpileup from update_114

---

requests/eggnog_mapper@9d1fbff733cf.yml
requests/genomescope@01210c4e9144.yml
requests/hisat2@f4af63aaf57a.yml
requests/interproscan@98cafcbd2578.yml
requests/keras_train_and_eval@e1317b5502fa.yml
requests/lofreq_call@4805fe3d8fda.yml
requests/maxquant@1f39c833f65f.yml
requests/metaspades@fd128c111ab0.yml
requests/quast@3061c8b029e5.yml
requests/samtools_view@5826298f6a73.yml

eggnog_mapper, interproscan and keras_train_and_eval do not have tests that could possibly pass because all of the tests use data tables.
genomescope, hisat2, lofreq_call, maxquant, metaspades, quast, samtools_view have a minority of test failures for data table tests or minor diffs.

[FORCE] tools from update 115

---

requests/hifi.yml

This is an update with the same version as what is installed.  The update pipeline would recognise this and skip tests but the install pipeline does not, so [FORCE] is necessary

[FORCE] hifiadapterfilt update

---

trusted_owners.yml

Add ebi-gxa to 'trusted' meaning the tools are updated by Jenkins.
We've been advised to skip the current revision of bakta and wait for the next one.

Trust ebi-gxa and mistrust current bakta revision

---

requests/bcftools_consensus@147de996e34f.yml
requests/bcftools_convert_to_vcf@4935320a59a8.yml
requests/bcftools_csq@f01b2c9506b9.yml
requests/bcftools_mpileup@03191140c66a.yml
requests/bcftools_norm@ebb2e12a6de1.yml
requests/bcftools_stats@a2f8dc22d7c0.yml
requests/ena_upload@a62c4a11a67d.yml
requests/ivar_trim@e3bb03cf207a.yml
requests/maxquant@4d17fcdeb8ff.yml
requests/metaphlan@6dee4abadccb.yml
requests/raxml@ea30d3089354.yml
requests/salmon@ebab418107f5.yml

bcftools_consensus, bcftools_convert_to_vcf, bcftools_csq, bcftools_mpileup, bcftools_norm, bcftools_stats, ena_upload, ivar_trim, maxquant, metaphlan, raxml, salmon
These mostly fail data table tests. Fine to update

[FORCE] tool from update 132

---

requests/scanpy_run_umap@0f98603d0116.yml

There's no test data in the tool shed repo but there is in the git repo, this passes on dev when running galaxy-tool-test with the git repo data as test data path.

[FORCE] install scanpy_run_umap

---

trusted_owners.yml

We can't automatically update tools from ebi-gxa because there are no test data files in the tool shed repositories, causing the tests to fail.
I'll add these tools to #864

Remove owner from trusted list due to lack of test data

---

jenkins/install_tools.sh
jenkins/requirements.yml

Update requirements, since there is a new version of ephemeris and finally no need to use the fork. Pin galaxy-tool-util and galaxy-util to versions that are compatible with one another.
Get the installation script to run each set of tool tests twice. This is a brute force attempt to solve the problem caused by the first test failing when there is a new biocontainer. This won't be necessary once we can use containers from the aarnet cvmfs stratum 1, and seems OK as an interim solution.

Update jenkins requirements and add an extra test to each installation

---

requests/seq_filter_by_id.yml

Bump version of seq_filter_by_id to get [this fix](https://github.com/peterjc/pico_galaxy/pull/41)
Resolves https://dhdnectar.freshdesk.com/a/tickets/190552 
Probably needs to be force installed like last time, but passes planemo test locally.

Bump seq_filter_by_id

---

requests/bakta_latest.yml
trusted_owners.yml

Install latest bakta. GA's version needs to be uninstalled and the data table entry removed because the loc file structure for bakta has changed and it will break galaxy if both exist.
Update: this is probably not the case and both versions can exist.

[FORCE] Bakta latest

---

requests/eu_iuc_tools_suite_filtered.yml

This is a subset of a longer list of iuc tools the Galaxy EU has and GA does not.
This is a draft until TPV has been altered so that all of these will run with singularity.

Install some IUC tools (part 1)

---

requests/kraken_taxonomy_report@latest.yml
requests/medaka_variant_pipeline@latest.yml
requests/raceid_filtnormconf@latest.yml
requests/samtools_bam_to_cram@latest.yml

kraken_taxonomy_report, medaka_variant_pipeline, raceid_filtnormconf, samtools_bam_to_cram
raceid_filtnormconf can't pass because of overly strict sim size comparison limits in tests, the rest use reference data in tests.

[FORCE] tools from install 1416

---

requests/mitohifi.yml

MitoHiFi is a python pipeline developed to finalize the assembly and annotation of mitogenomes.

MitoHiFi tool

---

requests/qiime2_core__tools__export@f47ed6c69f5d.yml
requests/qiime2_core__tools__import@10447a4b0cc3.yml

qiime2_core__tools__export and qiime2_core__tools__import have been updated this month. Owner q2d2 is not in the list of owners whose tools are automatically updated but probably should be

[FORCE] Update qiime2 tools

---

.env
jenkins/install_tools.sh
jenkins/requirements.yml

Remove second set of tests from staging server and remove testing from production altogether.
For some time, the tool tests on production immediately after installation have been chaotic. Tools are prone to fail tests because the API calls to get the test data or test files fail, and then the whole installation is rolled back. This could be due to multiple gunicorn processes or the migrations of galaxy's API to fastapi or something else. We can rely on the staging tests.

stop production testing

---

requests/dorado_update.yaml

These versions target 24.1 and use the `pod5` datatype. dorado will fail tests but I've tested it on dev. dorado_pod5_convert should pass tests.

update dorado wrapper

---

requests/gtn_20241004.yml

These two tools will enable 'qcxms-predictions' and 'GO-enrichment' tutorials.
GTN content is not completely covered on GA - there is some missingness in the Ecology section and miscellaneous tutorial tools that don't seem to be installed on other Galaxy servers and have unknown owners.

Add two more GTN tools

---

requests/alphafold-bump.yml

Just patched a bug running multimer with `disable_amber_relax`. Is it possible to run this before next wednesday? Or could I just manually update in the web admin?

[FORCE] Bump AlphaFold to version 2.3.2_2
